import {
  Home,
  MessageSquare,
  CalendarDays,
  Pill,
  RefreshCw,
  FileText,
  FlaskConical,
  Files,
  Stethoscope,
  ShieldCheck,
  Syringe,
  Bell,
  Settings,
  HeartPulse,
} from "lucide-react";
export const patientModules = [
  {
    tab: "POČETNA",
    slug: "",
    label: "Početna",
    description: "Osobni zdravstveni pregled",
    Icon: Home,
  },
  {
    tab: "POSJETI",
    slug: "posjeti",
    label: "Posjeti",
    description: "Povijest pregleda i preporuke liječnika",
    Icon: Stethoscope,
  },
  {
    tab: "KOMUNIKACIJA",
    slug: "komunikacija",
    label: "Komunikacija",
    description: "Razgovori s vašim liječnicima",
    Icon: MessageSquare,
  },
  {
    tab: "NARUDŽBE",
    slug: "narudzbe",
    label: "Narudžbe",
    description: "Bolnički pregledi, lokacije i upute",
    Icon: CalendarDays,
  },
  {
    tab: "TERMINI",
    slug: "termini",
    label: "Termini u ordinaciji",
    description: "Vaš kalendar obiteljske medicine",
    Icon: CalendarDays,
  },
  {
    tab: "UPUTNICE",
    slug: "uputnice",
    label: "Uputnice",
    description: "Izdane uputnice i njihova valjanost",
    Icon: FileText,
  },
  {
    tab: "LIJEKOVI",
    slug: "lijekovi",
    label: "Lijekovi",
    description: "Propisani i preuzeti lijekovi",
    Icon: Pill,
  },
  {
    tab: "OBNOVA LIJEKOVA",
    slug: "obnova",
    label: "Obnova lijekova",
    description: "Zahtjevi za obnovu odobrene terapije",
    Icon: RefreshCw,
  },
  {
    tab: "RECEPTI",
    slug: "recepti",
    label: "Recepti",
    description: "Dokumenti i digitalne potvrde recepata",
    Icon: FileText,
  },
  {
    tab: "LABORATORIJ",
    slug: "laboratorij",
    label: "Laboratorijski nalazi",
    description: "Rezultati, referentni intervali i PDF",
    Icon: FlaskConical,
  },
  {
    tab: "SPECIJALISTIČKI NALAZI",
    slug: "nalazi",
    label: "Specijalistički nalazi",
    description: "Nalazi, otpusna pisma i PDF",
    Icon: Stethoscope,
  },
  {
    tab: "PRIVITCI",
    slug: "vanjski-dokumenti",
    label: "Vanjski dokumenti",
    description: "Učitavanje i pregled vaših privitaka",
    Icon: Files,
  },
  {
    tab: "ISPRIČNICE",
    slug: "ispricnice",
    label: "Ispričnice",
    description: "Izdane ispričnice i provjera valjanosti",
    Icon: ShieldCheck,
  },
  {
    tab: "CIJEPLJENJA",
    slug: "cijepljenja",
    label: "Cijepljenja",
    description: "Doze, serije i evidencija cijepljenja",
    Icon: Syringe,
  },
  {
    tab: "TERAPIJA",
    slug: "terapija",
    label: "Terapija",
    description: "Aktivna i prethodna terapija",
    Icon: HeartPulse,
  },
  {
    tab: "KARTON",
    slug: "karton",
    label: "Zdravstveni karton",
    description: "Dijagnoze, pregledi i zdravstveni podaci",
    Icon: HeartPulse,
  },
  {
    tab: "DOKUMENTI",
    slug: "dokumenti",
    label: "Dokumenti",
    description: "Svi dokumenti izdani u sustavu",
    Icon: Files,
  },
  {
    tab: "OBAVIJESTI",
    slug: "obavijesti",
    label: "Obavijesti",
    description: "Promjene i nove zdravstvene informacije",
    Icon: Bell,
  },
  {
    tab: "POSTAVKE",
    slug: "postavke",
    label: "Postavke",
    description: "Profil, sigurnost i pristup kartonu",
    Icon: Settings,
  },
];
export function patientPath(tab: string) {
  const m = patientModules.find((m) => m.tab === tab);
  return "/moje" + (m?.slug ? "/" + m.slug : "");
}
