begin;
create table public.patient_access_blocks(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients(id),user_id uuid not null references public.profiles(id),blocked boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),unique(patient_id,user_id));
alter table public.patient_access_blocks enable row level security;revoke all on public.patient_access_blocks from anon,authenticated;
create trigger audit_change after insert or update on public.patient_access_blocks for each row execute function private.audit_change();
create trigger no_delete before delete on public.patient_access_blocks for each row execute function private.no_clinical_delete();
create function private.patient_allows(pid uuid,uid uuid) returns boolean language sql stable security definer set search_path='' as $$select not exists(select 1 from public.patient_access_blocks b where b.patient_id=pid and b.user_id=uid and b.blocked)$$;
create or replace function private.can_read_patient(pid uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.patients p where p.id=pid and p.archived_at is null and (
 (p.user_id=auth.uid() and private.has_role('PATIENT')) or (private.patient_allows(pid,auth.uid()) and (
 exists(select 1 from public.patient_doctors pd join public.doctors d on d.id=pd.doctor_id where pd.patient_id=p.id and pd.revoked_at is null and d.active and d.user_id=auth.uid() and private.has_role('DOCTOR',d.institution_id)) or
 exists(select 1 from public.patient_staff ps where ps.patient_id=p.id and ps.user_id=auth.uid() and ps.revoked_at is null and private.has_role('NURSE',ps.institution_id))))));$$;
create or replace function private.treating_doctor(pid uuid) returns uuid language sql stable security definer set search_path='' as $$
 select d.id from public.patient_doctors pd join public.doctors d on d.id=pd.doctor_id join public.patients p on p.id=pd.patient_id where pd.patient_id=pid and p.archived_at is null and pd.revoked_at is null and d.active and d.user_id=auth.uid() and private.has_role('DOCTOR',d.institution_id) and private.patient_allows(pid,auth.uid()) order by pd.is_primary desc,d.id limit 1;$$;
create or replace function private.can_schedule(pid uuid,did uuid) returns boolean language sql stable security definer set search_path='' as $$
 select private.patient_allows(pid,auth.uid()) and exists(select 1 from public.doctors d join public.patient_doctors pd on pd.doctor_id=d.id join public.patients p on p.id=pd.patient_id where d.id=did and pd.patient_id=pid and pd.revoked_at is null and d.active and p.archived_at is null and (
 (d.user_id=auth.uid() and private.has_role('DOCTOR',d.institution_id)) or (private.has_role('NURSE',d.institution_id) and exists(select 1 from public.patient_staff ps where ps.patient_id=pid and ps.user_id=auth.uid() and ps.institution_id=d.institution_id and ps.revoked_at is null))));$$;
create or replace function private.can_message(pid uuid,did uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.patient_doctors pd join public.doctors d on d.id=pd.doctor_id join public.patients p on p.id=pd.patient_id join public.institution_users iu on iu.user_id=d.user_id and iu.institution_id=d.institution_id join public.user_roles r on r.user_id=d.user_id and r.institution_id=d.institution_id and r.role='DOCTOR' where pd.patient_id=pid and d.id=did and pd.revoked_at is null and d.active and iu.active and p.archived_at is null and private.patient_allows(pid,d.user_id) and ((p.user_id=auth.uid() and private.has_role('PATIENT')) or (d.user_id=auth.uid() and private.has_role('DOCTOR',d.institution_id))))$$;
create function public.my_patient_settings() returns jsonb language plpgsql security definer set search_path='' as $$declare p public.patients;begin
 if not private.has_role('PATIENT') then raise exception 'Forbidden' using errcode='42501';end if;select * into p from public.patients where user_id=auth.uid() and archived_at is null;if p.id is null then return null;end if;
 perform private.audit_event('PATIENT_SETTINGS_VIEWED','patients',p.id);
 return jsonb_build_object('patient',jsonb_build_object('id',p.id,'name',p.first_name||' '||p.last_name,'birth_date',p.birth_date,'patient_number',p.patient_number,'phone',p.phone,'email',p.email,'address',p.address,'city',p.city,'postal_code',p.postal_code,'emergency_contact',p.emergency_contact),
 'team',(select coalesce(jsonb_agg(x),'[]') from(select d.user_id,d.display_name name,'DOCTOR' role,private.patient_allows(p.id,d.user_id) allowed from public.patient_doctors pd join public.doctors d on d.id=pd.doctor_id where pd.patient_id=p.id and pd.revoked_at is null and d.active
 union select ps.user_id,pr.first_name||' '||pr.last_name,'NURSE',private.patient_allows(p.id,ps.user_id) from public.patient_staff ps join public.profiles pr on pr.id=ps.user_id where ps.patient_id=p.id and ps.revoked_at is null)x));end $$;
create function public.save_patient_contacts(data jsonb) returns void language plpgsql security definer set search_path='' as $$declare pid uuid;begin
 select id into pid from public.patients where user_id=auth.uid() and archived_at is null;if pid is null or not private.has_role('PATIENT') then raise exception 'Forbidden' using errcode='42501';end if;
 if length(coalesce(data->>'phone',''))>50 or length(coalesce(data->>'email',''))>254 or length(coalesce(data->>'address',''))>300 or length(coalesce(data->>'city',''))>150 or length(coalesce(data->>'postal_code',''))>20 or length(coalesce(data->>'emergency_contact',''))>500 then raise exception 'Contact too long';end if;
 if coalesce(data->>'email','')<>'' and data->>'email' !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'Invalid email';end if;
 update public.patients set phone=nullif(trim(data->>'phone'),''),email=nullif(trim(data->>'email'),''),address=nullif(trim(data->>'address'),''),city=nullif(trim(data->>'city'),''),postal_code=nullif(trim(data->>'postal_code'),''),emergency_contact=nullif(trim(data->>'emergency_contact'),'') where id=pid;
 perform private.audit_event('PATIENT_CONTACTS_UPDATED','patients',pid);end $$;
create function public.set_my_care_access(target_user uuid,allowed boolean) returns void language plpgsql security definer set search_path='' as $$declare pid uuid;begin
 select id into pid from public.patients where user_id=auth.uid() and archived_at is null;if pid is null or not private.has_role('PATIENT') or allowed is null then raise exception 'Forbidden' using errcode='42501';end if;
 if not exists(select 1 from public.patient_doctors pd join public.doctors d on d.id=pd.doctor_id where pd.patient_id=pid and pd.revoked_at is null and d.user_id=target_user union select 1 from public.patient_staff ps where ps.patient_id=pid and ps.revoked_at is null and ps.user_id=target_user) then raise exception 'Assigned care team required';end if;
 insert into public.patient_access_blocks(patient_id,user_id,blocked,created_by) values(pid,target_user,not allowed,auth.uid()) on conflict(patient_id,user_id) do update set blocked=excluded.blocked,updated_at=now();
 perform private.audit_event('PATIENT_ACCESS_PREFERENCE_CHANGED','patients',pid);end $$;
create function public.my_access_history(page_number integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare pid uuid;result jsonb;begin
 select id into pid from public.patients where user_id=auth.uid() and archived_at is null;if pid is null or not private.has_role('PATIENT') or page_number is null or page_number not between 0 and 10000 then raise exception 'Forbidden' using errcode='42501';end if;
 select coalesce(jsonb_agg(x),'[]') into result from(select a.id,a.action,a.created_at,coalesce(nullif(trim(pr.first_name||' '||pr.last_name),''),'Sustav') actor from public.audit_logs a left join public.profiles pr on pr.id=a.user_id where (a.action like '%VIEWED' or a.action like '%DOWNLOADED') and (
 (a.entity_type in ('patients','medical_reports','medical_records','laboratory_orders','hospital_bookings') and a.entity_id=pid) or
 (a.entity_type='documents' and exists(select 1 from public.documents d where d.id=a.entity_id and d.patient_id=pid)) or
 (a.entity_type='document_attachments' and exists(select 1 from public.document_attachments d where d.id=a.entity_id and d.patient_id=pid))) order by a.created_at desc,a.id limit 50 offset page_number*50)x;return result;end $$;
revoke all on function private.patient_allows(uuid,uuid) from public,anon,authenticated;
revoke all on function public.my_patient_settings(),public.save_patient_contacts(jsonb),public.set_my_care_access(uuid,boolean),public.my_access_history(integer) from public,anon;
grant execute on function public.my_patient_settings(),public.save_patient_contacts(jsonb),public.set_my_care_access(uuid,boolean),public.my_access_history(integer) to authenticated;
commit;
