begin;
create sequence private.report_number;
create table public.medical_reports(id uuid primary key default gen_random_uuid(),number text not null unique default('EZ-NAL-'||extract(year from now())::text||'-'||lpad(nextval('private.report_number')::text,8,'0')),patient_id uuid not null references public.patients(id),doctor_id uuid not null references public.doctors(id),institution_id uuid not null references public.institutions(id),booking_id uuid references public.hospital_bookings(id),report_type text not null check(report_type in ('SPECIALIST','DISCHARGE')),reported_on date not null,diagnosis text not null default '' check(length(diagnosis)<=2000),content text not null check(length(trim(content)) between 2 and 20000),conclusion text not null default '' check(length(conclusion)<=10000),recommendations text not null default '' check(length(recommendations)<=10000),patient_name text not null,patient_number text not null,doctor_name text not null,institution_name text not null,specialty text not null,version integer not null default 1,supersedes_id uuid unique references public.medical_reports(id),superseded_by uuid unique references public.medical_reports(id),correction_reason text not null default '',created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),request_id uuid not null,unique(created_by,request_id));
create index reports_patient_idx on public.medical_reports(patient_id,reported_on desc);
alter table public.medical_reports enable row level security;revoke all on public.medical_reports from anon,authenticated;
create trigger no_delete before delete on public.medical_reports for each row execute function private.no_clinical_delete();
create trigger audit_change after insert or update on public.medical_reports for each row execute function private.audit_change();
create function private.preserve_medical_report() returns trigger language plpgsql set search_path='' as $$begin if (to_jsonb(new)-'superseded_by') is distinct from (to_jsonb(old)-'superseded_by') or old.superseded_by is not null then raise exception 'Create a new report version';end if;return new;end $$;
create trigger immutable_report before update on public.medical_reports for each row execute function private.preserve_medical_report();
create function public.publish_medical_report(patient_id uuid,booking_id uuid,previous_id uuid,data jsonb,request_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare did uuid:=private.treating_doctor(patient_id);prior public.medical_reports;p public.patients;d public.doctors;rid uuid;begin
 if booking_id is not null then select s.doctor_id into did from public.hospital_bookings b join public.hospital_slots sl on sl.id=b.slot_id join public.hospital_services s on s.id=sl.service_id where b.id=booking_id and b.patient_id=publish_medical_report.patient_id and b.status in ('ARRIVED','COMPLETED') and private.hospital_provider(s.id);end if;
 if did is null then raise exception 'Forbidden' using errcode='42501';end if;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||request_id::text,91));
 select id into rid from public.medical_reports r where r.created_by=auth.uid() and r.request_id=publish_medical_report.request_id and r.patient_id=publish_medical_report.patient_id;if rid is not null then return rid;end if;
 if previous_id is not null then select * into prior from public.medical_reports where id=previous_id for update;
 if prior.id is null or prior.patient_id<>patient_id or prior.doctor_id<>did or prior.superseded_by is not null or prior.booking_id is distinct from booking_id or length(trim(coalesce(data->>'correction_reason',''))) not between 5 and 1000 then raise exception 'Invalid report correction';end if;end if;
 if (data->>'reported_on')::date>current_date or (data->>'reported_on')::date<current_date-3650 then raise exception 'Invalid report date';end if;
 select * into p from public.patients where id=patient_id;select * into d from public.doctors where id=did;
 insert into public.medical_reports(patient_id,doctor_id,institution_id,booking_id,report_type,reported_on,diagnosis,content,conclusion,recommendations,patient_name,patient_number,doctor_name,institution_name,specialty,version,supersedes_id,correction_reason,created_by,request_id)
 values(patient_id,did,d.institution_id,booking_id,data->>'report_type',(data->>'reported_on')::date,coalesce(data->>'diagnosis',''),data->>'content',coalesce(data->>'conclusion',''),coalesce(data->>'recommendations',''),p.first_name||' '||p.last_name,p.patient_number,d.display_name,(select name from public.institutions where id=d.institution_id),d.specialty,coalesce(prior.version,0)+1,previous_id,coalesce(data->>'correction_reason',''),auth.uid(),request_id) returning id into rid;
 if previous_id is not null then update public.medical_reports set superseded_by=rid where id=previous_id;end if;
 if p.user_id is not null then insert into public.notifications(user_id,message) values(p.user_id,'Objavljen je novi specijalistički nalaz / otpusno pismo.');end if;
 perform private.audit_event('MEDICAL_REPORT_PUBLISHED','patients',patient_id);return rid;end $$;
create function private.can_read_report(r public.medical_reports) returns boolean language sql stable security definer set search_path='' as $$ select private.can_read_patient(r.patient_id) or (r.created_by=auth.uid() and private.has_role('DOCTOR',r.institution_id) and exists(select 1 from public.doctors d where d.id=r.doctor_id and d.active)) $$;
create function public.list_medical_reports(personal boolean,patient_filter uuid default null,page_number integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
 if auth.uid() is null or personal is null or page_number is null or page_number not between 0 and 10000 or (personal and not private.has_role('PATIENT')) then raise exception 'Forbidden' using errcode='42501';end if;
 select coalesce(jsonb_agg(x),'[]') into result from(select r.*,r.created_by=auth.uid() and private.has_role('DOCTOR',r.institution_id) and not personal can_amend from public.medical_reports r where (patient_filter is null or r.patient_id=patient_filter) and case when personal then exists(select 1 from public.patients p where p.id=r.patient_id and p.user_id=auth.uid()) else private.can_read_report(r) end order by r.created_at desc,r.id limit 50 offset page_number*50)x;
 perform private.audit_event('MEDICAL_REPORTS_VIEWED','patients',patient_filter);return result;end $$;
create function public.download_medical_report(report_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r public.medical_reports;begin select * into r from public.medical_reports where id=report_id;
 if r.id is null or not private.can_read_report(r) then raise exception 'Forbidden' using errcode='42501';end if;perform private.audit_event('MEDICAL_REPORT_DOWNLOADED','patients',r.patient_id);return to_jsonb(r);end $$;
create function public.download_laboratory_result(result_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r public.laboratory_results;o public.laboratory_orders;result jsonb;begin
 select * into r from public.laboratory_results where id=result_id;select * into o from public.laboratory_orders where id=r.order_id;
 if r.id is null or not(private.can_read_patient(o.patient_id) or private.has_role('LAB_TECHNICIAN',o.laboratory_institution_id)) then raise exception 'Forbidden' using errcode='42501';end if;
 select jsonb_build_object('number',o.number,'patient_name',p.first_name||' '||p.last_name,'patient_number',p.patient_number,'laboratory_name',i.name,'result',to_jsonb(r)||jsonb_build_object('author',pr.first_name||' '||pr.last_name,'parameters',(select coalesce(jsonb_agg(to_jsonb(v) order by v.code),'[]') from public.laboratory_parameters v where v.result_id=r.id))) into result from public.patients p,public.institutions i,public.profiles pr where p.id=o.patient_id and i.id=o.laboratory_institution_id and pr.id=r.created_by;
 perform private.audit_event('LAB_RESULT_DOWNLOADED','patients',o.patient_id);return result;end $$;
revoke all on function private.preserve_medical_report(),private.can_read_report(public.medical_reports) from public,anon,authenticated;
revoke all on function public.publish_medical_report(uuid,uuid,uuid,jsonb,uuid),public.list_medical_reports(boolean,uuid,integer),public.download_medical_report(uuid),public.download_laboratory_result(uuid) from public,anon;
grant execute on function public.publish_medical_report(uuid,uuid,uuid,jsonb,uuid),public.list_medical_reports(boolean,uuid,integer),public.download_medical_report(uuid),public.download_laboratory_result(uuid) to authenticated;
commit;
