begin;
create table public.hospital_services(
 id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.institutions(id),doctor_id uuid not null references public.doctors(id),name text not null check(length(trim(name)) between 2 and 150),specialty text not null check(length(trim(specialty)) between 2 and 150),location text not null check(length(trim(location)) between 2 and 300),instructions text not null default '' check(length(instructions)<=2000),active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.hospital_slots(id uuid primary key default gen_random_uuid(),service_id uuid not null references public.hospital_services(id),starts_at timestamptz not null,duration_minutes integer not null check(duration_minutes between 5 and 240),priority_only boolean not null default false,active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(service_id,starts_at));
create table public.hospital_bookings(id uuid primary key default gen_random_uuid(),slot_id uuid not null references public.hospital_slots(id),patient_id uuid not null references public.patients(id),referring_doctor_id uuid not null references public.doctors(id),referral_id uuid references public.documents(id),priority boolean not null default false,priority_reason text not null default '' check(length(priority_reason)<=1000),status text not null default 'BOOKED' check(status in ('BOOKED','ARRIVED','COMPLETED','CANCELLED','NO_SHOW')),version integer not null default 1,cancellation_reason text,request_id uuid not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(created_by,request_id));
create unique index hospital_slot_booked on public.hospital_bookings(slot_id) where status<>'CANCELLED';
create unique index hospital_referral_booked on public.hospital_bookings(referral_id) where status<>'CANCELLED';
create index hospital_patient_idx on public.hospital_bookings(patient_id,created_at desc);
create index hospital_slot_time_idx on public.hospital_slots(service_id,starts_at);
create table public.hospital_booking_history(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.hospital_bookings(id),snapshot jsonb not null,created_at timestamptz not null default now(),created_by uuid references public.profiles(id));
do $$declare t text;begin foreach t in array array['hospital_services','hospital_slots','hospital_bookings','hospital_booking_history'] loop
 execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);
 execute format('create trigger no_delete before delete on public.%I for each row execute function private.no_clinical_delete()',t);
 execute format('create trigger audit_change after insert or update on public.%I for each row execute function private.audit_change()',t);
end loop;end $$;
create function private.hospital_admin(org uuid) returns boolean language sql stable security definer set search_path='' as $$select private.has_role('SYSTEM_ADMIN') or private.has_role('INSTITUTION_ADMIN',org)$$;
create function private.hospital_provider(service uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.hospital_services s join public.doctors d on d.id=s.doctor_id where s.id=service and d.active and d.user_id=auth.uid() and private.has_role('DOCTOR',s.institution_id))$$;
create function public.hospital_context(manage boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$begin
 if auth.uid() is null or not(private.has_role('DOCTOR') or private.has_role('SYSTEM_ADMIN') or private.has_role('INSTITUTION_ADMIN')) then raise exception 'Forbidden' using errcode='42501';end if;
 return jsonb_build_object('services',(select coalesce(jsonb_agg(to_jsonb(s)||jsonb_build_object('institution_name',i.name,'doctor_name',d.display_name) order by i.name,s.name),'[]') from public.hospital_services s join public.institutions i on i.id=s.institution_id join public.doctors d on d.id=s.doctor_id where i.active and i.archived_at is null and case when manage then private.hospital_admin(i.id) else s.active and d.active end),
 'institutions',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'name',i.name)),'[]') from public.institutions i where manage and i.active and private.hospital_admin(i.id)),
 'doctors',(select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'institution_id',d.institution_id,'display_name',d.display_name)),'[]') from public.doctors d where manage and d.active and private.hospital_admin(d.institution_id)));
end $$;
create function public.save_hospital_service(service_id uuid,data jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare org uuid:=(data->>'institution_id')::uuid;did uuid:=(data->>'doctor_id')::uuid;sid uuid;begin
 if not private.hospital_admin(org) then raise exception 'Forbidden' using errcode='42501';end if;
 if not exists(select 1 from public.doctors d join public.institution_users m on m.user_id=d.user_id and m.institution_id=d.institution_id join public.user_roles r on r.user_id=d.user_id and r.institution_id=d.institution_id and r.role='DOCTOR' where d.id=did and d.institution_id=org and d.active and m.active) then raise exception 'Active institution doctor required';end if;
 if service_id is null then insert into public.hospital_services(institution_id,doctor_id,name,specialty,location,instructions,created_by) values(org,did,trim(data->>'name'),trim(data->>'specialty'),trim(data->>'location'),coalesce(data->>'instructions',''),auth.uid()) returning id into sid;
 else select id into sid from public.hospital_services s where s.id=service_id and s.institution_id=org and s.doctor_id=did for update;if sid is null then raise exception 'Service identity cannot change';end if;
 update public.hospital_services set active=(data->>'active')::boolean,updated_at=now() where id=sid;end if;
 perform private.audit_event('HOSPITAL_SERVICE_SAVED','hospital_services',sid);return sid;end $$;
create function public.publish_hospital_slots(service_id uuid,local_start timestamp,duration integer,slot_count integer,priority_only boolean default false) returns void language plpgsql security definer set search_path='' as $$declare s public.hospital_services;st timestamptz:=local_start at time zone 'Europe/Zagreb';n integer;begin
 select * into s from public.hospital_services where id=service_id;
 if s.id is null or not private.hospital_admin(s.institution_id) then raise exception 'Forbidden' using errcode='42501';end if;
 if not s.active or st is null or st<=now() or st>now()+interval '2 years' or (st at time zone 'Europe/Zagreb')<>local_start or duration is null or duration not between 5 and 240 or slot_count is null or slot_count not between 1 and 48 then raise exception 'Invalid slots';end if;
 perform pg_advisory_xact_lock(hashtextextended(s.doctor_id::text,71));
 if exists(select 1 from public.hospital_slots sl join public.hospital_services hs on hs.id=sl.service_id where hs.doctor_id=s.doctor_id and sl.active and sl.starts_at<st+make_interval(mins=>duration*slot_count) and sl.starts_at+make_interval(mins=>sl.duration_minutes)>st) then raise exception 'Doctor slots overlap';end if;
 for n in 0..slot_count-1 loop insert into public.hospital_slots(service_id,starts_at,duration_minutes,priority_only,created_by) values(service_id,st+make_interval(mins=>n*duration),duration,priority_only,auth.uid());end loop;
 perform private.audit_event('HOSPITAL_SLOTS_PUBLISHED','hospital_services',service_id);end $$;
create function public.list_hospital_slots(service_id uuid,date_from date,date_to date,manage boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$declare s public.hospital_services;begin
 select * into s from public.hospital_services where id=service_id;
 if s.id is null or not (case when manage then private.hospital_admin(s.institution_id) else private.has_role('DOCTOR') end) then raise exception 'Forbidden' using errcode='42501';end if;
 if date_from is null or date_to is null or date_to<date_from or date_to-date_from>93 then raise exception 'Range up to 93 days';end if;
 return (select coalesce(jsonb_agg(x order by x.starts_at),'[]') from(select sl.*,exists(select 1 from public.hospital_bookings b where b.slot_id=sl.id and b.status<>'CANCELLED') booked from public.hospital_slots sl where sl.service_id=list_hospital_slots.service_id and sl.starts_at>=date_from::timestamp at time zone 'Europe/Zagreb' and sl.starts_at<(date_to+1)::timestamp at time zone 'Europe/Zagreb' and (manage or (s.active and sl.active and sl.starts_at>now() and not exists(select 1 from public.hospital_bookings b where b.slot_id=sl.id and b.status<>'CANCELLED'))) order by sl.starts_at limit 500)x);end $$;
create function public.close_hospital_slot(slot_id uuid) returns void language plpgsql security definer set search_path='' as $$declare sl public.hospital_slots;org uuid;begin
 select * into sl from public.hospital_slots where id=slot_id for update;select institution_id into org from public.hospital_services where id=sl.service_id;
 if org is null or not private.hospital_admin(org) then raise exception 'Forbidden' using errcode='42501';end if;
 if exists(select 1 from public.hospital_bookings b where b.slot_id=sl.id and b.status<>'CANCELLED') then raise exception 'Booked slot cannot close';end if;
 update public.hospital_slots set active=false where id=slot_id;perform private.audit_event('HOSPITAL_SLOT_CLOSED','hospital_slots',slot_id);end $$;
create function private.hospital_booking_changed() returns trigger language plpgsql security definer set search_path='' as $$begin
 if TG_OP='UPDATE' then insert into public.hospital_booking_history(booking_id,snapshot,created_by) values(old.id,to_jsonb(old),auth.uid());end if;
 insert into public.notifications(user_id,message) select p.user_id,'Bolnička narudžba: '||case new.status when 'BOOKED' then 'termin je potvrđen.' when 'CANCELLED' then 'termin je otkazan.' when 'COMPLETED' then 'pregled je završen.' else 'status je promijenjen.' end from public.patients p where p.id=new.patient_id and p.user_id is not null;
 insert into public.schedule_events(user_id,revision) select d.user_id,gen_random_uuid() from public.doctors d where d.id=new.referring_doctor_id or d.id=(select s.doctor_id from public.hospital_slots sl join public.hospital_services s on s.id=sl.service_id where sl.id=new.slot_id) on conflict(user_id) do update set revision=excluded.revision;
 return new;end $$;
create trigger hospital_booking_changed after insert or update on public.hospital_bookings for each row execute function private.hospital_booking_changed();
create function public.book_hospital_slot(patient_id uuid,slot_id uuid,referral_id uuid,priority boolean,priority_reason text,request_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare did uuid:=private.treating_doctor(patient_id);sl public.hospital_slots;s public.hospital_services;prior public.hospital_bookings;result uuid;begin
 if did is null then raise exception 'Forbidden' using errcode='42501';end if;
 if request_id is null or priority is null or (priority and length(trim(coalesce(priority_reason,''))) not between 5 and 1000) then raise exception 'Priority reason required';end if;
 perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||request_id::text,72));
 select * into prior from public.hospital_bookings b where b.created_by=auth.uid() and b.request_id=book_hospital_slot.request_id;
 if prior.id is not null then if prior.patient_id<>patient_id or prior.slot_id<>slot_id or prior.referral_id is distinct from referral_id or prior.priority<>priority then raise exception 'Request reused';end if;return prior.id;end if;
 perform pg_advisory_xact_lock(hashtextextended(patient_id::text,73));
 select * into sl from public.hospital_slots where id=slot_id for update;select * into s from public.hospital_services where id=sl.service_id;
 if sl.id is null or not sl.active or not s.active or sl.starts_at<=now() or (sl.priority_only and not priority) or not exists(select 1 from public.institutions i where i.id=s.institution_id and i.active and i.archived_at is null) then raise exception 'Slot unavailable';end if;
 if exists(select 1 from public.hospital_bookings b where b.slot_id=sl.id and b.status<>'CANCELLED') then raise exception 'Slot already booked';end if;
 if referral_id is not null and not exists(select 1 from public.documents d where d.id=referral_id and d.patient_id=book_hospital_slot.patient_id and d.kind='REFERRAL' and d.status='ISSUED' and d.expires_on>=current_date) then raise exception 'Valid patient referral required';end if;
 if exists(select 1 from public.hospital_bookings b join public.hospital_slots bs on bs.id=b.slot_id where b.patient_id=book_hospital_slot.patient_id and b.status<>'CANCELLED' and bs.starts_at<sl.starts_at+make_interval(mins=>sl.duration_minutes) and bs.starts_at+make_interval(mins=>bs.duration_minutes)>sl.starts_at) then raise exception 'Patient already has overlapping booking';end if;
 insert into public.hospital_bookings(patient_id,slot_id,referring_doctor_id,referral_id,priority,priority_reason,request_id,created_by) values(patient_id,slot_id,did,referral_id,priority,case when priority then trim(priority_reason) else '' end,request_id,auth.uid()) returning id into result;
 perform private.audit_event('HOSPITAL_BOOKING_CREATED','hospital_bookings',result);return result;end $$;
create function public.list_hospital_bookings(mode text,patient_filter uuid default null,page_number integer default 0) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
 if auth.uid() is null or mode is null or mode not in ('CARE','PERSONAL','PROVIDER') or page_number is null or page_number not between 0 and 10000 then raise exception 'Invalid request';end if;
 select coalesce(jsonb_agg(x order by x.starts_at desc),'[]') into result from(select b.*,sl.starts_at,sl.duration_minutes,s.name service_name,s.specialty,s.location,s.instructions,i.name institution_name,d.display_name specialist_name,p.first_name||' '||p.last_name patient_name,p.patient_number,
 (mode='CARE' and private.treating_doctor(p.id) is not null) or (mode='PERSONAL' and p.user_id=auth.uid() and private.has_role('PATIENT')) or (mode='PROVIDER' and private.hospital_provider(s.id)) can_cancel,
 mode='PROVIDER' and private.hospital_provider(s.id) can_process
 from public.hospital_bookings b join public.hospital_slots sl on sl.id=b.slot_id join public.hospital_services s on s.id=sl.service_id join public.institutions i on i.id=s.institution_id join public.doctors d on d.id=s.doctor_id join public.patients p on p.id=b.patient_id
 where (patient_filter is null or b.patient_id=patient_filter) and case mode when 'PERSONAL' then p.user_id=auth.uid() and private.has_role('PATIENT') when 'PROVIDER' then private.hospital_provider(s.id) else private.treating_doctor(p.id) is not null end order by sl.starts_at desc,b.id limit 50 offset page_number*50)x;
 perform private.audit_event('HOSPITAL_BOOKINGS_VIEWED','hospital_bookings',patient_filter);return result;end $$;
create function public.change_hospital_booking(booking_id uuid,expected_version integer,new_status text,reason text default '') returns void language plpgsql security definer set search_path='' as $$declare b public.hospital_bookings;sl public.hospital_slots;provider boolean;owner boolean;begin
 select * into b from public.hospital_bookings where id=booking_id for update;select * into sl from public.hospital_slots where id=b.slot_id;provider:=private.hospital_provider(sl.service_id);
 owner:=exists(select 1 from public.patients p where p.id=b.patient_id and p.user_id=auth.uid() and private.has_role('PATIENT'));
 if b.id is null or not(provider or owner or private.treating_doctor(b.patient_id) is not null) then raise exception 'Forbidden' using errcode='42501';end if;
 if b.version is distinct from expected_version then raise exception 'Booking changed' using errcode='40001';end if;
 if new_status='CANCELLED' and b.status='BOOKED' and length(trim(coalesce(reason,''))) between 5 and 500 and (not owner or sl.starts_at>now()) then null;
 elsif provider and sl.starts_at::date<=current_date and ((new_status in ('ARRIVED','NO_SHOW') and b.status='BOOKED') or (new_status='COMPLETED' and b.status='ARRIVED')) then null;
 else raise exception 'Invalid status transition';end if;
 update public.hospital_bookings set status=new_status,version=version+1,updated_at=now(),cancellation_reason=case when new_status='CANCELLED' then trim(reason) else null end where id=booking_id;
 perform private.audit_event('HOSPITAL_BOOKING_'||new_status,'hospital_bookings',booking_id);end $$;
revoke all on function private.hospital_admin(uuid),private.hospital_provider(uuid),private.hospital_booking_changed() from public,anon,authenticated;
revoke all on function public.hospital_context(boolean),public.save_hospital_service(uuid,jsonb),public.publish_hospital_slots(uuid,timestamp,integer,integer,boolean),public.list_hospital_slots(uuid,date,date,boolean),public.close_hospital_slot(uuid),public.book_hospital_slot(uuid,uuid,uuid,boolean,text,uuid),public.list_hospital_bookings(text,uuid,integer),public.change_hospital_booking(uuid,integer,text,text) from public,anon;
grant execute on function public.hospital_context(boolean),public.save_hospital_service(uuid,jsonb),public.publish_hospital_slots(uuid,timestamp,integer,integer,boolean),public.list_hospital_slots(uuid,date,date,boolean),public.close_hospital_slot(uuid),public.book_hospital_slot(uuid,uuid,uuid,boolean,text,uuid),public.list_hospital_bookings(text,uuid,integer),public.change_hospital_booking(uuid,integer,text,text) to authenticated;
commit;
