begin;
create table public.vaccinations(id uuid primary key default gen_random_uuid(),patient_id uuid not null references public.patients(id),doctor_id uuid not null references public.doctors(id),institution_id uuid not null references public.institutions(id),vaccine text not null check(length(trim(vaccine)) between 2 and 200),target_disease text not null check(length(trim(target_disease)) between 2 and 200),dose text not null check(length(trim(dose)) between 1 and 100),administered_on date not null,batch text not null check(length(trim(batch)) between 1 and 100),next_dose_on date,notes text not null default '' check(length(notes)<=2000),supersedes_id uuid unique references public.vaccinations(id),superseded_by uuid unique references public.vaccinations(id),correction_reason text not null default '',created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),request_id uuid not null,unique(created_by,request_id),check(next_dose_on is null or next_dose_on>administered_on));
create index vaccination_patient_idx on public.vaccinations(patient_id,administered_on desc);
alter table public.vaccinations enable row level security;revoke all on public.vaccinations from anon,authenticated;
create trigger audit_change after insert or update on public.vaccinations for each row execute function private.audit_change();
create trigger no_delete before delete on public.vaccinations for each row execute function private.no_clinical_delete();
create trigger immutable_record before update on public.vaccinations for each row execute function private.preserve_medical_report();
create function public.record_vaccination(patient_id uuid,previous_id uuid,data jsonb,request_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare did uuid:=private.treating_doctor(patient_id);prior public.vaccinations;vid uuid;begin
 if did is null then raise exception 'Forbidden' using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text||request_id::text,93));
 select id into vid from public.vaccinations v where v.created_by=auth.uid() and v.request_id=record_vaccination.request_id and v.patient_id=record_vaccination.patient_id;if vid is not null then return vid;end if;
 if previous_id is not null then select * into prior from public.vaccinations where id=previous_id for update;if prior.id is null or prior.patient_id<>patient_id or prior.doctor_id<>did or prior.superseded_by is not null or length(trim(coalesce(data->>'correction_reason',''))) not between 5 and 1000 then raise exception 'Invalid correction';end if;end if;
 if (data->>'administered_on')::date>current_date or (data->>'administered_on')::date<(select birth_date from public.patients where id=patient_id) then raise exception 'Invalid date';end if;
 insert into public.vaccinations(patient_id,doctor_id,institution_id,vaccine,target_disease,dose,administered_on,batch,next_dose_on,notes,supersedes_id,correction_reason,created_by,request_id) select patient_id,did,d.institution_id,trim(data->>'vaccine'),trim(data->>'target_disease'),trim(data->>'dose'),(data->>'administered_on')::date,trim(data->>'batch'),nullif(data->>'next_dose_on','')::date,coalesce(data->>'notes',''),previous_id,coalesce(data->>'correction_reason',''),auth.uid(),request_id from public.doctors d where d.id=did returning id into vid;
 if previous_id is not null then update public.vaccinations set superseded_by=vid where id=previous_id;end if;
 insert into public.notifications(user_id,message) select p.user_id,'Dodana je evidencija cijepljenja.' from public.patients p where p.id=patient_id and p.user_id is not null;
 perform private.audit_event('VACCINATION_RECORDED','patients',patient_id);return vid;end $$;
create function public.list_vaccinations(personal boolean,patient_filter uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;begin
 if auth.uid() is null or personal is null or (personal and not private.has_role('PATIENT')) then raise exception 'Forbidden' using errcode='42501';end if;
 select coalesce(jsonb_agg(x),'[]') into result from(select v.*,d.display_name doctor_name,i.name institution_name,not personal and v.created_by=auth.uid() and private.treating_doctor(v.patient_id) is not null can_amend from public.vaccinations v join public.doctors d on d.id=v.doctor_id join public.institutions i on i.id=v.institution_id join public.patients p on p.id=v.patient_id where (patient_filter is null or v.patient_id=patient_filter) and case when personal then p.user_id=auth.uid() else private.can_read_patient(v.patient_id) end order by v.administered_on desc,v.created_at desc limit 500)x;
 perform private.audit_event('VACCINATIONS_VIEWED','patients',patient_filter);return result;end $$;
revoke all on function public.record_vaccination(uuid,uuid,jsonb,uuid),public.list_vaccinations(boolean,uuid) from public,anon;
grant execute on function public.record_vaccination(uuid,uuid,jsonb,uuid),public.list_vaccinations(boolean,uuid) to authenticated;
commit;
